name: ' Job Summaries test'

on:
  workflow_dispatch:

defaults:
  run:
    shell: powershell

permissions:
  actions: read
  contents: read
  id-token: write
  pages: read

env:
  workflowDepth: 1
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Initialization:
    needs: [ ]
    runs-on: [ windows-latest ]
    steps:
      - name: CreateSummary1
        id: CreateSummary1
        run: |
          for ($i = 0; $i -lt 1000; $i++) {
            $s = "A" * 1000
            Add-Content -Encoding UTF8 -path $ENV:GITHUB_STEP_SUMMARY -value "$s"
          }

      - name: CreateSummary2
        id: CreateSummary2
        run: |
          for ($i = 0; $i -lt 1023; $i++) {
            $s = "B" * 1024
            Add-Content -Encoding UTF8 -path $ENV:GITHUB_STEP_SUMMARY -value "$s"
          }

      - name: CreateSummary3
        id: CreateSummary3
        run: |
          for ($i = 0; $i -lt 1024; $i++) {
            $s = "C" * 1024
            Add-Content -Encoding UTF8 -path $ENV:GITHUB_STEP_SUMMARY -value "$s"
          }
